/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTA10 (coord M9), SW3
  @{ */
#define BOARD_INITPINS_SW3_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_INITPINS_SW3_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITPINS_SW3_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_SW3_GPIO_PIN 10U                      /*!<@brief PORTA pin index: 10 */
#define BOARD_INITPINS_SW3_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_SW3_PIN 10U                           /*!<@brief PORTA pin index: 10 */
#define BOARD_INITPINS_SW3_CHANNEL 10                        /*!<@brief GPIOA GPIO channel: 10 */
#define BOARD_INITPINS_SW3_PIN_NAME PTA10                    /*!<@brief Pin name */
#define BOARD_INITPINS_SW3_LABEL "SW3"                       /*!<@brief Label */
#define BOARD_INITPINS_SW3_NAME "SW3"                        /*!<@brief Identifier name */
#define BOARD_INITPINS_SW3_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                             /* @} */

/*! @name PORTC4 (coord A9), J1[4]/UART1_TX/FTM0_CH3/FB_AD11
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PERIPHERAL UART1                        /*!<@brief Device name: UART1 */
#define BOARD_INITPINS_DEBUG_UART_TX_SIGNAL TX                               /*!<@brief UART1 signal: TX */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTC                              /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 4U                                  /*!<@brief PORTC pin index: 4 */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_NAME UART1_TX                       /*!<@brief Pin name */
#define BOARD_INITPINS_DEBUG_UART_TX_LABEL "J1[4]/UART1_TX/FTM0_CH3/FB_AD11" /*!<@brief Label */
#define BOARD_INITPINS_DEBUG_UART_TX_NAME "DEBUG_UART_TX"                    /*!<@brief Identifier name */
#define BOARD_INITPINS_DEBUG_UART_TX_DIRECTION kPIN_MUX_DirectionOutput      /*!<@brief Direction */
                                                                             /* @} */

/*! @name PORTC3 (coord A11), J1[2]/UART1_RX/FTM0_CH2/CLKOUT
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PERIPHERAL UART1                       /*!<@brief Device name: UART1 */
#define BOARD_INITPINS_DEBUG_UART_RX_SIGNAL RX                              /*!<@brief UART1 signal: RX */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTC                             /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 3U                                 /*!<@brief PORTC pin index: 3 */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_NAME UART1_RX                      /*!<@brief Pin name */
#define BOARD_INITPINS_DEBUG_UART_RX_LABEL "J1[2]/UART1_RX/FTM0_CH2/CLKOUT" /*!<@brief Label */
#define BOARD_INITPINS_DEBUG_UART_RX_NAME "DEBUG_UART_RX"                   /*!<@brief Identifier name */
                                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
